PROGRAMME prgm;
var nb1, nb2, nb3, nb4, nb5;
debut
    nb1:= 1+2+3;
    nb2:= 3*2-1;
    nb3:= 2-3*5+10/2*5;
    nb4:= (2-3)*5+(10/2)*5;
    nb5:= -5--2+3/1+-2;
    ecrire('resultat de 1+2+3: ', nb1);
    ecrire();
    ecrire('resultat de 3*2-1: ', nb2);
    ecrire();
    ecrire('resultat de 2-3*5+10/2*5: ', nb3);
    ecrire();
    ecrire('resultat de (2-3)*5+(10/2)*5: ', nb4);
    ecrire();
    ecrire('resultat de -5--2+3/1+-2: ', nb5);
fin
